variables:
  APP_NAME: "th2-python-service-generator"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "1"
  MAINTENANCE_VERSION: '0'
  ARTIFACTORY_PUBLISH_ENABLED: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
